# Generated by Django 5.2.3 on 2025-10-06 04:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('opening_time', models.TimeField(verbose_name='開店時刻')),
                ('closing_time', models.TimeField(verbose_name='閉店時刻')),
                ('preparation_minutes', models.IntegerField(default=60, verbose_name='準備時間（分）')),
                ('cleanup_minutes', models.IntegerField(default=60, verbose_name='片付け時間（分）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('fixed', '固定勤務'), ('flexible', 'フレキシブル勤務')], max_length=20, verbose_name='雇用形態')),
                ('hourly_wage', models.IntegerField(verbose_name='時給（円）')),
                ('hall_skill_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='ホールスキル（1-5）')),
                ('kitchen_skill_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='キッチンスキル（1-5）')),
                ('is_manager', models.BooleanField(default=False, verbose_name='責任者フラグ')),
                ('max_weekly_hours', models.IntegerField(default=40, verbose_name='週最大労働時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
            },
        ),
        migrations.CreateModel(
            name='StaffRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], verbose_name='曜日')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('required_staff', models.IntegerField(verbose_name='必要人数')),
                ('required_managers', models.IntegerField(default=1, verbose_name='必要責任者数')),
                ('required_hall_skill', models.IntegerField(default=0, verbose_name='必要ホールスキル人数')),
                ('required_kitchen_skill', models.IntegerField(default=0, verbose_name='必要キッチンスキル人数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '必要人数設定',
                'verbose_name_plural': '必要人数設定',
                'unique_together': {('store', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
