# Generated by Django 5.2.7 on 2025-10-20 06:48

from django.db import migrations, models


def generate_employee_ids(apps, schema_editor):
    """既存のスタッフに社員IDを生成"""
    Staff = apps.get_model('accounts', 'Staff')
    
    for staff in Staff.objects.all():
        if not staff.employee_id:
            # 店舗コード（3桁）+ 連番（4桁）の形式
            store_code = str(staff.store.id).zfill(3)
            
            # 同じ店舗の最大連番を取得
            last_staff = Staff.objects.filter(
                store=staff.store,
                employee_id__startswith=store_code
            ).exclude(id=staff.id).order_by('-employee_id').first()
            
            if last_staff and last_staff.employee_id:
                try:
                    last_number = int(last_staff.employee_id[-4:])
                    new_number = last_number + 1
                except (ValueError, IndexError):
                    new_number = 1
            else:
                # 同じ店舗のスタッフの数を基準にする
                new_number = Staff.objects.filter(
                    store=staff.store,
                    id__lte=staff.id
                ).count()
            
            staff.employee_id = f"{store_code}{str(new_number).zfill(4)}"
            staff.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='社員ID'),
        ),
        migrations.RunPython(generate_employee_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='社員ID'),
        ),
    ]
