# Generated by Django 5.2.7 on 2025-10-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
    ]
