# Generated by Django 5.2.7 on 2025-10-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='cleanup_minutes',
        ),
        migrations.RemoveField(
            model_name='store',
            name='preparation_minutes',
        ),
        migrations.AddField(
            model_name='store',
            name='dinner_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ディナー営業開始時刻'),
        ),
        migrations.AddField(
            model_name='store',
            name='last_order_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ラストオーダー時刻'),
        ),
        migrations.AddField(
            model_name='store',
            name='lunch_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ランチタイム終了時刻'),
        ),
        migrations.AddField(
            model_name='store',
            name='service_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='営業開始時刻'),
        ),
    ]
