# Generated by Django 5.2.7 on 2025-10-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_store_cleanup_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_break_time',
            field=models.BooleanField(default=False, verbose_name='中休憩の有無'),
        ),
    ]
