# Generated by Django 5.2.7 on 2025-10-27 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_store_has_break_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='shift_submission_deadline_day',
            field=models.IntegerField(default=20, help_text='各月の何日までシフト提出が可能か（1-28日）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='シフト提出締切日'),
        ),
        migrations.AddField(
            model_name='store',
            name='shift_submission_start_day',
            field=models.IntegerField(default=1, help_text='各月の何日からシフト提出が可能になるか（1-28日）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='シフト提出開始日'),
        ),
    ]
