# Generated by Django 5.2.3 on 2025-10-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='勤務日')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='確定フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff', verbose_name='スタッフ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'シフト',
                'verbose_name_plural': 'シフト',
                'unique_together': {('staff', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='希望日')),
                ('request_type', models.CharField(choices=[('off', '休み希望'), ('work', '勤務希望')], max_length=20, verbose_name='種別')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='希望開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='希望終了時刻')),
                ('is_locked', models.BooleanField(default=False, verbose_name='編集ロック')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '希望シフト',
                'verbose_name_plural': '希望シフト',
                'unique_together': {('staff', 'date', 'request_type')},
            },
        ),
    ]
