# Generated by Django 5.2.7 on 2025-10-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
    ]
