# Generated by Django 5.2.7 on 2025-10-29 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_store_shift_submission_deadline_day_and_more'),
        ('shift', '0002_shift_end_date_shiftrequest_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_min_staff', models.PositiveIntegerField(default=2, verbose_name='平日最小人数')),
                ('weekday_max_staff', models.PositiveIntegerField(default=5, verbose_name='平日最大人数')),
                ('weekend_min_staff', models.PositiveIntegerField(default=3, verbose_name='休日最小人数')),
                ('weekend_max_staff', models.PositiveIntegerField(default=6, verbose_name='休日最大人数')),
                ('service_hours_min_staff', models.PositiveIntegerField(default=3, verbose_name='営業時間中最小人数')),
                ('service_hours_max_staff', models.PositiveIntegerField(default=6, verbose_name='営業時間中最大人数')),
                ('after_last_order_min_staff', models.PositiveIntegerField(default=2, verbose_name='ラストオーダー後最小人数')),
                ('after_last_order_max_staff', models.PositiveIntegerField(default=4, verbose_name='ラストオーダー後最大人数')),
                ('lunch_time_min_staff', models.PositiveIntegerField(blank=True, default=2, null=True, verbose_name='ランチタイム中最小人数')),
                ('lunch_time_max_staff', models.PositiveIntegerField(blank=True, default=4, null=True, verbose_name='ランチタイム中最大人数')),
                ('dinner_time_min_staff', models.PositiveIntegerField(default=3, verbose_name='ディナータイム中最小人数')),
                ('dinner_time_max_staff', models.PositiveIntegerField(default=6, verbose_name='ディナータイム中最大人数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'シフト設定',
                'verbose_name_plural': 'シフト設定',
                'unique_together': {('store',)},
            },
        ),
    ]
