# Generated by Django 5.2.7 on 2025-11-24 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_announcement'),
        ('shift', '0003_shiftsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交代希望日')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('status', models.CharField(choices=[('open', '募集中'), ('closed', '締切'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='open', max_length=20, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='accounts.staff', verbose_name='募集者')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.shift', verbose_name='対象シフト')),
            ],
            options={
                'verbose_name': 'シフト交代募集',
                'verbose_name_plural': 'シフト交代募集',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='希望開始時刻')),
                ('end_time', models.TimeField(verbose_name='希望終了時刻')),
                ('status', models.CharField(choices=[('pending', '待機中'), ('accepted', '承認済み'), ('rejected', '却下'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='状態')),
                ('message', models.TextField(blank=True, verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff', verbose_name='立候補者')),
                ('swap_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shift.shiftswaprequest', verbose_name='シフト交代募集')),
            ],
            options={
                'verbose_name': 'シフト交代立候補',
                'verbose_name_plural': 'シフト交代立候補',
                'ordering': ['-created_at'],
                'unique_together': {('swap_request', 'applicant')},
            },
        ),
    ]
