# Generated by Django 5.2.8 on 2025-12-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_announcement'),
        ('shift', '0004_shiftswaprequest_shiftswapapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('staff_staff', 'スタッフ同士'), ('staff_manager', 'スタッフ-管理者'), ('swap_request', 'シフト交代関連')], default='staff_staff', max_length=20, verbose_name='ルームタイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_participant1', to='accounts.staff', verbose_name='参加者1')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_participant2', to='accounts.staff', verbose_name='参加者2')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='店舗')),
                ('swap_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='shift.shiftswapapplication', verbose_name='シフト交代立候補')),
                ('swap_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='shift.shiftswaprequest', verbose_name='シフト交代申請')),
            ],
            options={
                'verbose_name': 'チャットルーム',
                'verbose_name_plural': 'チャットルーム',
                'ordering': ['-updated_at'],
                'unique_together': {('participant1', 'participant2', 'swap_request')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.staff', verbose_name='送信者')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shift.chatroom', verbose_name='チャットルーム')),
            ],
            options={
                'verbose_name': 'チャットメッセージ',
                'verbose_name_plural': 'チャットメッセージ',
                'ordering': ['created_at'],
            },
        ),
    ]
